filter:
    excluded_paths:
        - 'tests/*'

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        newline_at_end_of_file: true
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            utility_class_name: '^[A-Z][a-zA-Z0-9]*$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^((?:[a-z]|__)[a-zA-Z0-9]*|test[A-Z][_a-zA-Z0-9]*)$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^(m[0-9a-z_]+|[A-Z][a-zA-Z0-9]*)$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: '^(?:is|can|has|should|may|supports)'

coding_style:
   php:
       indentation:
           general:
               use_tabs: false
               size: 4
           switch:
               indent_case: true
       spaces:
           general:
               linefeed_character: newline
           before_parentheses:
               function_declaration: false
               closure_definition: true
               function_call: false
               if: true
               for: true
               while: true
               switch: true
               catch: true
               array_initializer: false
           around_operators:
               assignment: true
               logical: true
               equality: true
               relational: true
               bitwise: true
               additive: true
               multiplicative: true
               shift: true
               unary_additive: false
               concatenation: true
               negation: false
           before_left_brace:
               class: true
               function: true
               if: true
               else: true
               for: true
               while: true
               do: true
               switch: true
               try: true
               catch: true
               finally: true
           before_keywords:
               else: true
               while: true
               catch: true
               finally: true
           within:
               brackets: false
               array_initializer: false
               grouping: false
               function_call: false
               function_declaration: false
               if: false
               for: false
               while: false
               switch: false
               catch: false
               type_cast: false
           ternary_operator:
               before_condition: true
               after_condition: true
               before_alternative: true
               after_alternative: true
               in_short_version: false
           other:
               before_comma: false
               after_comma: true
               before_semicolon: false
               after_semicolon: true
               after_type_cast: true
       braces:
           classes_functions:
               class: new-line
               function: new-line
               closure: end-of-line
           if:
               opening: end-of-line
               always: true
               else_on_new_line: false
           for:
               opening: end-of-line
               always: true
           while:
               opening: end-of-line
               always: true
           do_while:
               opening: end-of-line
               always: true
               while_on_new_line: false
           switch:
               opening: end-of-line
           try:
               opening: end-of-line
               catch_on_new_line: false
               finally_on_new_line: false
       upper_lower_casing:
           keywords:
               general: lower
           constants:
               true_false_null: lower

tools:
    external_code_coverage:
        timeout: 2400
        runs: 1