name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest
      - name: Test
        run: |
          - vendor/bin/phpcs --standard=./ruleset.xml src/
          - vendor/bin/phpstan analyse -l 7 -c phpstan.neon.dist src/
          - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
